FROM hub.regene.xyz/dockerhub_proxy/library/httpd:latest

RUN echo "Asia/Jakarta" > /etc/timezone
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install Python and pip (adjust for your specific Apache base image's OS)
RUN apt-get update && apt-get install -y python3 python3-venv && rm -rf /var/lib/apt/lists/*

# Create a virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN chown -R www-data:www-data /usr/local/apache2

RUN mkdir -p /var/www/html && \
    chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html 

WORKDIR /app
COPY requirements-http.txt .
# untuk konfigurasi http nanti
# COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf

ENV PYTHONPATH=/app
RUN pip install --no-cache-dir -r requirements-http.txt
RUN pip install --upgrade certifi

USER www-data
COPY --chown=www-data . .
RUN rm -rf src/update

# CMD src/prepare_gbr.sh