name: 'Check staging branch'

on:
  pull_request:
    branches:
      - staging
jobs:
  check_staging_branch:
    runs-on: ubuntu-latest
    steps:
      # - name: cek
        # run: echo "base ${{ gitea.base_ref }} , head ref ${{ gitea.head_ref }}"
      - name: Check branch
        if: gitea.base_ref == 'staging' && gitea.head_ref != 'stable'
        # if: gitea.base_ref != 'stable'
        run: |
          echo "ERROR: You can only merge to ${{gitea.base_ref}} from ${{ gitea.head_ref }}."
          exit 1          
